package com.triangle.classification.application.database.dynamo.triangle.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Triangle")
public class TriangleEntity {

    private String id;
    private String sideA;
    private String sideB;
    private String sideC;
    private String type;

    public TriangleEntity(String sideA, String sideB, String sideC, String type) {
        this.sideA = sideA;
        this.sideB = sideB;
        this.sideC = sideC;
        this.type = type;
    }


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "sideA")
    public String getSideA() {
        return sideA;
    }

    @DynamoDBAttribute(attributeName = "sideB")
    public String getSideB() {
        return sideB;
    }

    @DynamoDBAttribute(attributeName = "sideC")
    public String getSideC() {
        return sideC;
    }

    @DynamoDBAttribute(attributeName = "type")
    public String getType() {
        return type;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setSideA(String sideA) {
        this.sideA = sideA;
    }

    public void setSideB(String sideB) {
        this.sideB = sideB;
    }

    public void setSideC(String sideC) {
        this.sideC = sideC;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "Triangle{" +
                "id=" + id +
                ", sideA=" + sideA +
                ", sideB=" + sideB +
                ", sideC=" + sideC +
                ", type='" + type + '\'' +
                '}';
    }
}
